import '../../data/models/AddAddressModel/add_address_model.dart';
import '../../data/models/AddToCartModel/addTo_cart_model.dart';
import '../../data/models/AllAddressesModel/all_addresses_model.dart';
import '../../data/models/CommonModel/common_model.dart';
import '../../data/models/FavouritesModel/favourites_model.dart';
import '../../data/models/FetchUserModel/fetch_user_model.dart';
import '../../data/models/HomeModel/home_model.dart';
import '../../data/models/MlmModels/mlm_downlines_model.dart';
import '../../data/models/MyAllServicesModel/my_all_services_model.dart';
import '../../data/models/NearWorkshopModel/near_workshop_model.dart';
import '../../data/models/OrderHistoryModel/order_history_model.dart';
import '../../data/models/ProductModel/product_model.dart';
import '../../data/models/RemFromCartModel/rem_from_cart_model.dart';
import '../../data/models/RemFromFevModel/rem_from_fev_model.dart';
import '../../data/models/SearchModel/search_model.dart';
import '../../data/models/ServicesModel/services_model.dart';
import '../../data/models/TransactionModel/transaction_model.dart';
import '../../data/models/UpdateAddressModel/update_address_model.dart';
import '../../data/models/UpdateCartQuantityModel/update_cart_quantity_model.dart';
import '../../data/models/ViewCartModel/view_cart_model.dart';
import '../../data/models/ViewFavouritesModel/view_favourites_model.dart';
import '../../data/models/Wallet/AllUpiIdModel/add_upi_id_model.dart';
import '../../data/models/Wallet/AllUpiIdModel/delete_upi_id_model.dart';
import '../../data/models/Wallet/AllUpiIdModel/get_all_upi_id_model.dart';
import '../../data/models/Wallet/WithdrawHistoryModel/withdraw_history_model.dart';
import '../../data/models/Wallet/WithdrawModel/withdraw_model.dart';
import '../../data/models/login_and_registration_flow/login/LoginModel.dart';
import '../../data/models/login_and_registration_flow/registration/RegisterModel.dart';

abstract class ApiRepository {

  Future<LoginModel> login(Map<String,String> request);
  Future<CommonModel> registerOtp(Map<String, String> request);
  Future<RegisterModel> register(Map<String, String> request);
  Future<CommonModel> resetPassword(Map<String, String> request);
  Future<ProductModel> getAllProductsList();
  Future<SearchModel> searchProduct(Map<String, String> request);
  Future<UpdateAddressModel> updateAddress(String addressId,Map<String, dynamic> request);
  // Future<CommonModel> addAddress(Map<String, String> request);
  Future<TransactionModel> createOrder(Map<String, dynamic> request);
  Future<CommonModel> verifyOrder(Map<String, dynamic> request);
  Future<OrderHistoryModel> myOrderHistory(Map<String, String> request);
  Future<NearWorkshopModel> getAllWorkshopList(Map<String, String> request);
  Future<NearWorkshopModel> getBreakdownList(Map<String, String> request);
  Future<AddToCartModel> addToCart(Map<String, dynamic> request);
  Future<FavouritesModel> addToFavourites(Map<String, String> request);
  Future<ViewCartModel> getAllCartList();
  Future<UpdateCartQuantityModel> updateCartQuantity(Map<String, dynamic> request);
  Future<ViewFavouritesModel> getAllFavouriteList();
  Future<void> logOut(Map<String, String> request);
  Future<RemFromCartModel> removeFromCart(Map<String, String> request);
  Future<RemFromFevModel> removeFromFavourite(Map<String, String> request);
  Future<OrderHistoryModel> cancelOrder(Map<String, String> request);
  Future<ServiceModel> bookBreakdownService(Map<String, String> request);
  Future<ServiceModel> bookWorkshopService(Map<String, String> request);
  // Future<CustomerServicesModel> myServices(String customerId);
  Future<MyAllServicesModel> myAllServices();
  Future<void> refreshToken(Map<String, String> request);
  Future<HomeModel> getHomeData();
  Future<MyAllServicesModel> cancelService(Map<String, String> request);
  Future<HomeModel> getFeaturedWorkshop(Map<String, String> request);
  Future<AllAddressesModel> getAllAddress();
  Future<AddAddressModel> addAddress(Map<String, dynamic> request);
  Future<GetUpiIdModel> getAllUpiId();
  Future<AddUpiIdModel> addAllUpiId(Map<String, dynamic> request);
  Future<DeleteUpiIdModel> deleteUpiId(Map<String, dynamic> request);
  Future<WithdrawModel> createWithdraw(Map<String, dynamic> request);
  Future<WithdrawHistoryModel> withdrawalHistory();
  Future<MlmDownLinesModel> getAllDownLines(Map<String,dynamic> request);
  Future<CommonModel> deleteAddress(String id);
  Future<FetchUserModel> fetchUserData();
}