// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0fC53btA4FnqnmXC3XyvOFHa0lirFgJk',
    appId: '1:255529326168:web:4c7d68275d4b68b92d1c2d',
    messagingSenderId: '255529326168',
    projectId: 'hangzo-app-3ea24',
    authDomain: 'hangzo-app-3ea24.firebaseapp.com',
    storageBucket: 'hangzo-app-3ea24.firebasestorage.app',
    measurementId: 'G-GGFFM89T5P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyghZg2VLDn5XivmB8cztaFKek9qz1gmY',
    appId: '1:255529326168:android:4ef420bab3f36f0b2d1c2d',
    messagingSenderId: '255529326168',
    projectId: 'hangzo-app-3ea24',
    storageBucket: 'hangzo-app-3ea24.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnP_lUtL7DNeA46sb7IzUsMEWvzilrrsQ',
    appId: '1:255529326168:ios:2b64b43a92442b312d1c2d',
    messagingSenderId: '255529326168',
    projectId: 'hangzo-app-3ea24',
    storageBucket: 'hangzo-app-3ea24.firebasestorage.app',
    iosBundleId: 'com.example.hungzoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnP_lUtL7DNeA46sb7IzUsMEWvzilrrsQ',
    appId: '1:255529326168:ios:2b64b43a92442b312d1c2d',
    messagingSenderId: '255529326168',
    projectId: 'hangzo-app-3ea24',
    storageBucket: 'hangzo-app-3ea24.firebasestorage.app',
    iosBundleId: 'com.example.hungzoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0fC53btA4FnqnmXC3XyvOFHa0lirFgJk',
    appId: '1:255529326168:web:9caac873fb57cdd42d1c2d',
    messagingSenderId: '255529326168',
    projectId: 'hangzo-app-3ea24',
    authDomain: 'hangzo-app-3ea24.firebaseapp.com',
    storageBucket: 'hangzo-app-3ea24.firebasestorage.app',
    measurementId: 'G-GBJ54NQLMV',
  );

}